export { default as Favicon } from "/public/images/favicon.png"
export { default as LogoImage } from "/public/images/logo.svg"
export { default as LogoImageLight } from "/public/images/logo_light.svg"

export { default as PhoneIcon } from "/public/images/phone_icon.svg"
export { default as EnvelopeIcon } from "/public/images/envelope_icon.svg"
export { default as PlayBtnIcon } from "/public/images/play_btn.svg"

export { default as PhotoMainBanner } from "/public/images/main_banner.png"
export { default as PhotoMainBannerVector } from "/public/images/main_banner_vector.svg"
export { default as PhotoAboutBlock } from "/public/images/about_block_bg.svg"
export { default as PhotoSolutionHighlight } from "/public/images/solution_highlight.png"
export { default as PhotoSpotlight_01 } from "/public/images/spotlight_01.png"
export { default as PhotoSpotlight_02 } from "/public/images/spotlight_02.png"
export { default as PhotoSpotlight_03 } from "/public/images/spotlight_03.png"
export { default as PhotoSubscribe } from "/public/images/subscribe_vector.svg"
export { default as PhotoVector_01 } from "/public/images/vector_01.svg"
export { default as PhotoVector_02 } from "/public/images/vector_02.svg"
export { default as PhotoVector_03 } from "/public/images/vector_03.svg"

export { default as LineIconBriefcase } from "/public/images/line-icon-briefcase.svg"
export { default as LineIconCurrent } from "/public/images/line-icon-current.svg"
export { default as LineIconUpward } from "/public/images/line-icon-upward.svg"

export { default as PhotoUser_01 } from "/public/images/users/01.jpg"
export { default as PhotoUser_02 } from "/public/images/users/02.jpg"
export { default as PhotoUser_03 } from "/public/images/users/03.jpg"
export { default as PhotoUser_04 } from "/public/images/users/04.jpg"
export { default as PhotoUser_05 } from "/public/images/users/05.jpg"
export { default as PhotoUser_06 } from "/public/images/users/06.jpg"
export { default as PhotoUser_07 } from "/public/images/users/07.jpg"
export { default as PhotoUser_08 } from "/public/images/users/08.jpg"
export { default as PhotoUser_09 } from "/public/images/users/09.jpg"
export { default as PhotoUser_10 } from "/public/images/users/10.jpg"

export { default as SocialTwitter } from "/public/images/social-twitter.svg"
export { default as SocialFacebook } from "/public/images/social-facebook.svg"
export { default as SocialLinkedin } from "/public/images/social-linkedin.svg"
export { default as SocialInstagram } from "/public/images/social-instagram.svg"
